//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardChecker
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocManagement
    {
        public int ID { get; set; }
        public string DocumentTitle { get; set; }
        public string DocumentCode { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsAlternativeDoc { get; set; }
        public Nullable<bool> IsInvalid { get; set; }
        public Nullable<int> SourceDoc { get; set; }
    }
}
